global using Xunit;
global using Castle.Core.Logging;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Todo.Application.Commands.Requests;
global using Todo.Domain.Commands.Handlers;
global using Todo.Domain.Contracts.Repositories;
global using Todo.Domain.Contracts.Services;
